### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by Croydon** [silash35/qpdftools#16]
I just found your app via Flathub and noticed that you did copy the Adobe Acrobat icon. This is neither legal nor useful to symbolize a different application. You should change it as soon as possible to avoid legal trouble.

**Comment by silash35** [comment]
I'm not a very good icon designer, but I'll try to think of something better. Probably just PDF written in capital letters.

Thank you for letting me know

**Comment by silash35** [comment]
Done. I will close this issue.

I believe that the new icon is an improvement. It remains similar to the Qt icon, you can still tell that it is an app for PDFs and the new icon has more details (I made it based on the KDE icons).

Yes, putting the name of the application on the icon is far from ideal, but that's what I could think of.
